app/concepts/api/v1/users/accounts/contracts/create.rb, app/controllers/application_controller.rb, config/initializers/constants/error_codes.rb
Updated error code constants with unique validations for usernames, phone numbers, and emails. Enhanced creation contracts in API to utilize these new error codes. Also included additional error parsing to handle parameter parsing issues within ApplicationController, improving overall error handling.
=> Add unique validation and error parsing enhancements

Gemfile, app/concepts/api/v1/locations/contracts/index.rb, app/concepts/api/v1/locations/operations/index.rb, app/concepts/api/v1/locations/queries/index.rb, app/concepts/api/v1/locations/serializers/city_serializer.rb, app/concepts/api/v1/locations/serializers/index_serializer.rb, app/concepts/api/v1/locations/serializers/neighborhood_serializer.rb, app/concepts/api/v1/locations/serializers/state_serializer.rb, app/controllers/api/v1/locations_controller.rb, app/lib/services/alba_json.rb, app/lib/services/compose_render_hash.rb, app/lib/services/fast_json.rb, app/models/city.rb, app/models/country.rb, app/models/neighborhood.rb, app/models/seed_task.rb, app/models/state.rb, config/routes.rb, db/files/states_cities.json, db/migrate/20240704163112_create_countries.rb, db/migrate/20240704163123_create_states.rb, db/migrate/20240704163134_create_cities.rb, db/migrate/20240704163145_create_neighborhoods.rb, db/migrate/20240704180612_create_seed_tasks.rb, db/schema.rb, db/seeds.rb
Add location-related operations, models, and serializers
This commit introduces various new entities tied to the locations domain, providing a structure for representing countries, states, cities, and neighborhoods in the application. Multiple operations, such as location index and filter, are implemented. Each new model also has its' corresponding serializer for proper data rendering.
=> Feature/dng 170 cities&neigboorhood endpoint

app/concepts/api/v1/users/accounts/contracts/change_status.rb, app/concepts/api/v1/users/accounts/operations/change_status.rb, app/concepts/api/v1/users/accounts/serializers/user_account.rb, app/concepts/api/v1/users/accounts/serializers/user_profile.rb, app/concepts/application_operation.rb, app/controllers/api/v1/admin/users_controller.rb, app/lib/services/compose_render_hash.rb, app/models/user_account.rb, config/locales/custom_error_messages.yml, config/routes.rb, db/migrate/20240705002308_add_status_to_user_account.rb, db/schema.rb
This commit introduces the ability to change the status of a user's account. A new 'status' field has been added to the UserAccount model, and new validation and operations have been set up to handle status changes. Furthermore, routes and controllers have been updated to facilitate this new feature.
=> Add user account status change functionality

config/environments/development.rb, config/environments/test.rb, config/initializers/jwt_session.rb
The configuration for JWT token store has been updated to fetch from environment variables, allowing for more flexible configuration. The configuration settings in the test and development environment files have also been commented out to prevent redundancy and potential conflicts.
=> Update JWT token store configuration

app/controllers/health_checks_controller.rb, config/routes.rb
A new controller, HealthChecksController, has been created to manage health checks. Additionally, a route named 'health_check' has been added that maps to the 'show' action of the new controller. This will respond with a simple 'ok' status, which can be used to verify the health and accessibility of the application.
=> Add HealthChecksController and route

app/concepts/api/v1/users/sessions/contracts/create.rb, db/seeds.rb
The seeds file for user accounts has been updated to match database changes. Various fields have been added and removed in the user profile creation section. Furthermore, user sessions validation in the API has been simplified. Extraneous fields and checks have been removed from the user session creation contract, improving readability and performance.
=> Update user account seeds and simplify user sessions validation

app/concepts/api/v1/users/sessions/operations/create.rb, app/concepts/api/v1/users/sessions/serializers/create.rb, app/models/user_account.rb, config/initializers/constants/error_codes.rb
The code updates error handling within the user authentication process, replacing a localized error message with 'unauthorized'. Additionally, a new unique error code (user_account_without_confirmation) is introduced. The user model is also adjusted to delegate 'email' instead of 'slug'. Furthermore, 'email' field is added in user session serialization.
=> Update authentication error handling and user model

app/concepts/api/v1/cities/operations/update.rb, app/concepts/api/v1/countries/contracts/update.rb, app/concepts/api/v1/lib/errors/custom_error.rb, app/concepts/api/v1/lib/serializers/errors/data.rb, app/concepts/api/v1/lib/serializers/errors/hash.rb, app/concepts/api/v1/states/contracts/update.rb, app/concepts/api/v1/teams/contracts/create.rb, app/concepts/api/v1/teams/contracts/update.rb, app/concepts/api/v1/users/accounts/contracts/create.rb, app/concepts/api/v1/users/accounts/operations/change_status.rb, app/concepts/api/v1/users/accounts/operations/confirm.rb, app/concepts/api/v1/users/sessions/contracts/create.rb, app/concepts/api/v1/users/sessions/operations/create.rb, app/concepts/api/v1/users/sessions/operations/refresh_token.rb, app/concepts/application_operation.rb, app/controllers/authorized_api_controller.rb, app/controllers/concerns/authentication.rb, app/controllers/concerns/endpoint.rb, app/lib/error_formater.rb, app/lib/services/compose_render_hash.rb, app/policies/application_policy.rb, db/migrate/20240711140955_rolify_create_roles.rb
Created a new ErrorFormater class to standardize and streamline how errors are handled and returned. This was then incorporated into various areas of the codebase, replacing and refactoring the previous ad hoc error messaging approaches. This resulted in more consistent and efficient error handling overall, leading to improved error messaging in the application's responses.
=> Add ErrorFormater class and refactor error handling across application

app/concepts/api/v1/lib/queries/query_helper.rb, app/concepts/api/v1/users/accounts/contracts/change_status.rb, app/concepts/api/v1/users/accounts/contracts/index.rb, app/concepts/api/v1/users/accounts/operations/index.rb, app/concepts/api/v1/users/accounts/queries/index.rb, app/concepts/api/v1/users/accounts/serializers/city.rb, app/concepts/api/v1/users/accounts/serializers/index.rb, app/concepts/api/v1/users/accounts/serializers/neighborhood.rb, app/concepts/api/v1/users/accounts/serializers/organization.rb, app/concepts/api/v1/users/accounts/serializers/user_account.rb, app/concepts/api/v1/users/accounts/serializers/user_profile.rb, app/concepts/api/v1/users/lib/check_account_active.rb, app/concepts/api/v1/users/sessions/operations/create.rb, app/controllers/api/v1/users_controller.rb, app/controllers/authorized_api_controller.rb, app/models/city.rb, app/models/neighborhood.rb, app/models/team_member.rb, app/models/user_account.rb, app/models/user_profile.rb, config/initializers/constants/user.rb, config/routes.rb, db/migrate/20240713025305_change_team_member_relation.rb, db/migrate/20240713060915_change_status_and_locked_to_user_account.rb, db/schema.rb
Implemented user account filters to allow for more efficient data queries. Updated corresponding operations and serializers to support the enhanced filtering capability. Also, introduced status options in user accounts and adjusted the database schema and model associations to better support the application's structure and functionality.
=> Add user accounts filters, operations and serializers

app/concepts/api/v1/users/accounts/operations/show_current_user.rb, app/concepts/api/v1/users/accounts/serializers/show_current_user.rb, app/controllers/api/v1/users_controller.rb, app/models/user_account.rb, config/routes.rb
This commit introduces a function to show the current user's account details. It includes the creation of two new classes: 'ShowCurrentUser' under both Operations and Serializers modules. In addition, an endpoint has been added to the UsersController. Minor adjustments have also been made to the UserAccount model and the routes configuration.
=> Add 'show current user' functionality

app/concepts/api/v1/lib/queries/query_helper.rb, app/concepts/api/v1/lib/serializers/naming_convention.rb, app/concepts/api/v1/organizations/contracts/create.rb, app/concepts/api/v1/organizations/contracts/index.rb, app/concepts/api/v1/organizations/operations/create.rb, app/concepts/api/v1/organizations/operations/index.rb, app/concepts/api/v1/organizations/queries/index.rb, app/concepts/api/v1/roles/contracts/update.rb, app/concepts/api/v1/roles/operations/update.rb, app/concepts/api/v1/roles/serializers/update.rb, app/concepts/api/v1/teams/operations/create.rb, app/concepts/api/v1/teams/serializers/member.rb, app/concepts/api/v1/users/accounts/contracts/index.rb, app/concepts/api/v1/users/accounts/queries/index.rb, app/concepts/api/v1/users/accounts/serializers/show_current_user.rb, app/controllers/api/v1/roles_controller.rb, app/models/permission.rb, app/models/role.rb, app/models/role_permission.rb, app/models/state.rb, config/initializers/constants/error_codes.rb, config/initializers/constants/user.rb, config/routes.rb, db/migrate/20240715215647_add_delete_at_to_roles.rb, db/migrate/20240717051134_add_primary_key_to_role_permissions.rb, db/schema.rb
Added the update operation for roles, along with necessary changes to models and validations. This also introduces new changes to the migrate file, schema and serializers related to roles. Furthermore, refinements in existing files such as code optimisation and adjustments were made.
=> Implement role update feature and related changes

app/concepts/api/v1/roles/contracts/create.rb, app/concepts/api/v1/roles/operations/create.rb, app/concepts/api/v1/roles/operations/index.rb, app/concepts/api/v1/roles/serializers/create.rb, app/concepts/api/v1/teams/contracts/create.rb, app/concepts/api/v1/teams/contracts/update.rb, app/concepts/api/v1/teams/operations/index.rb, app/concepts/api/v1/teams/operations/show.rb, app/concepts/api/v1/teams/operations/update.rb, app/concepts/api/v1/teams/queries/index.rb, app/concepts/api/v1/teams/serializers/index.rb, app/concepts/api/v1/teams/serializers/show.rb, app/concepts/api/v1/teams/serializers/user_profile.rb, app/concepts/api/v1/users/accounts/contracts/create.rb, app/concepts/api/v1/users/accounts/contracts/update.rb, app/concepts/api/v1/users/accounts/operations/create.rb, app/concepts/api/v1/users/accounts/operations/show_current_user.rb, app/concepts/api/v1/users/accounts/operations/update.rb, app/concepts/api/v1/users/accounts/serializers/show_current_user.rb, app/concepts/api/v1/users/accounts/serializers/user_profile.rb, app/controllers/api/v1/roles_controller.rb, app/controllers/api/v1/users_controller.rb, app/models/role.rb, app/models/team.rb, app/models/user_account.rb, app/models/user_profile.rb, config/initializers/constants/error_codes.rb, config/routes.rb, db/migrate/20240718064608_change_team_relations_to_user_profile.rb, db/schema.rb
This commit includes the addition of new validation contracts, operations, and serializers for the concepts of user accounts, roles, and teams to manage the creation and updating of these entities. A functionality to check if attributes such as names, ids and permissions already exist before validation is also introduced. Updates to the "Teams" concept to associate with user profiles rather than team members are also included in this commit. Database schema is updated to reflect these changes with the inclusion of new foreign keys and references.
=> Implement new user account, role and team functionalities

app/concepts/api/v1/roles/serializers/update.rb, app/concepts/api/v1/users/sessions/operations/create.rb, config/environments/development.rb, config/initializers/constants/error_codes.rb, config/routes.rb
Added a new serializer for updating roles in API v1 and improved security settings for Sidekiq. Also, addressed a new condition for account status during user session creation and enhanced error handling during account validation. Performance improvements were made for development environment configs.
=> Implement enhancements in role serializers and security settings

Gemfile, app/concepts/api/v1/roles/serializers/update.rb, app/concepts/api/v1/users/sessions/operations/create.rb, config/environments/development.rb, config/initializers/constants/error_codes.rb, config/routes.rb
Added a new serializer for updating roles in API v1 and improved security settings for Sidekiq. Also, addressed a new condition for account status during user session creation and enhanced error handling during account validation. Performance improvements were made for development environment configs.
=> Securize sidekiq web ui

app/concepts/api/v1/users/accounts/serializers/index.rb
=> Users Serializer

app/concepts/api/v1/users/accounts/operations/show.rb, app/concepts/api/v1/users/accounts/serializers/show.rb, app/controllers/api/v1/organizations_controller.rb, app/controllers/api/v1/users_controller.rb, app/models/user_profile.rb, config/routes.rb
Added a new 'show' endpoint to the users API for displaying individual user profiles. This involved creating and integrating the corresponding operation, serializer, and route. Roles have also been delegated to the user account in the UserProfile model.
=> Added a new 'show' endpoint to the users

Gemfile, app/models/breeding_site_type.rb, app/models/container_type.rb, app/models/elimination_method_type.rb, app/models/place.rb, app/models/water_source_type.rb, config/application.rb, config/sidekiq.yml, db/migrate/20240725035612_create_active_storage_tables.active_storage.rb, db/migrate/20240725035821_create_breeding_site_types.rb, db/migrate/20240725035831_create_container_types.rb, db/migrate/20240725035838_create_elimination_method_types.rb, db/migrate/20240725035850_create_water_source_types.rb, db/migrate/20240725035902_create_places.rb, db/schema.rb, db/seeds.rb
Introduced new models: BreedingSiteType, ContainerType, EliminationMethodType, Place, and WaterSourceType. Created corresponding migrations and seed data. Configured Active Storage for container type images and updated ActiveStorage migration. Removed sidekiq-limit_fetch and sidekiq-scheduler gems.
=> Add models and seed data for site management

app/concepts/api/v1/special_places/contracts/create.rb, app/concepts/api/v1/special_places/contracts/destroy.rb, app/concepts/api/v1/special_places/contracts/index.rb, app/concepts/api/v1/special_places/contracts/update.rb, app/concepts/api/v1/special_places/operations/create.rb, app/concepts/api/v1/special_places/operations/destroy.rb, app/concepts/api/v1/special_places/operations/index.rb, app/concepts/api/v1/special_places/operations/show.rb, app/concepts/api/v1/special_places/operations/update.rb, app/concepts/api/v1/special_places/queries/index.rb, app/concepts/api/v1/special_places/queries/update.rb, app/concepts/api/v1/special_places/serializers/index.rb, app/concepts/api/v1/special_places/serializers/show.rb, app/controllers/api/v1/special_places_controller.rb, app/models/special_place.rb, config/routes.rb, db/migrate/20240730140540_create_special_places.rb, db/schema.rb, db/seeds.rb
Introduced create, read, update, and delete functionalities for SpecialPlaces. This includes new migration, models, serializers, and operations in Nested Modules. Routes and schema updated accordingly.
=> Add SpecialPlaces endpoints with CRUD operations

app/concepts/api/v1/organizations/operations/index.rb, app/concepts/api/v1/roles/operations/index.rb, app/concepts/api/v1/users/accounts/operations/index.rb, app/concepts/api/v1/users/accounts/queries/index.rb, config/initializers/pagy.rb
Modified several API operations to set default sorting parameters when none are provided. Also changed the Pagy overflow behavior to serve the last page instead of an empty page for better user experience.
=> Update sorting defaults in API operations and pagination config

app/concepts/api/v1/cities/contracts/create.rb, app/concepts/api/v1/cities/contracts/update.rb, app/concepts/api/v1/cities/operations/update.rb, app/concepts/api/v1/lib/serializers/naming_convention.rb, app/concepts/api/v1/states/operations/show.rb, app/concepts/api/v1/states/serializers/show.rb, app/concepts/api/v1/users/accounts/operations/index.rb, app/concepts/api/v1/users/accounts/queries/index.rb
Added state_id and country_id to neighborhoods attributes during city update. Changed neighborhood existence check to use name instead of id. Simplified and streamlined queries and serializers for better performance and accuracy.
=> Update validation, query includes, and serialization logic

app/controllers/api/v1/locations_controller.rb, app/controllers/api/v1/organizations_controller.rb, app/controllers/api/v1/users/accounts_controller.rb
Removed unnecessary permission checks for the index action in OrganizationsController and the create action in AccountsController. Also updated LocationsController to inherit from ApiController instead of AuthorizedApiController.
=> Simplify access permissions for index and create actions

app/concepts/api/v1/cities/contracts/create.rb, app/concepts/api/v1/cities/operations/create.rb, app/controllers/concerns/authentication.rb, config/initializers/constants/permission_codes.rb
Refactor city creation to handle neighborhoods attributes more robustly, including setting state_id and country_id for each neighborhood. Add error checking for unique city names within states. Update exception response format in authentication and introduce new permission codes for cities.
=> Update city creation logic and enhance authorization

app/concepts/api/v1/cities/contracts/update.rb, app/concepts/api/v1/houses/contracts/index.rb, app/concepts/api/v1/houses/operations/index.rb, app/concepts/api/v1/houses/queries/index.rb, app/concepts/api/v1/houses/serializers/index.rb, app/concepts/api/v1/roles/contracts/update.rb, app/concepts/api/v1/roles/operations/update.rb, app/concepts/api/v1/teams/serializers/index.rb, app/concepts/api/v1/users/sessions/serializers/create.rb, app/controllers/api/v1/houses_controller.rb, app/models/application_record.rb, app/models/house.rb, app/models/house_block.rb, app/models/team.rb, config/routes.rb, db/migrate/20240808035809_add_name_to_house_blocks.rb, db/schema.rb, db/seeds.rb
This commit introduces an index endpoint for houses within the API. It includes new operations, contracts, serializers, and queries to handle house-related data efficiently. Additionally, it includes a database schema change to add a name to house_blocks and important seed data adjustments.
=> Add houses index endpoint and related components

app/concepts/api/v1/teams/contracts/index.rb, app/concepts/api/v1/teams/queries/index.rb, app/concepts/api/v1/teams/serializers/index.rb, app/concepts/api/v1/teams/serializers/show.rb, app/concepts/api/v1/users/accounts/contracts/index.rb, app/concepts/api/v1/users/accounts/queries/index.rb
Added member attribute to serializers with full name and ID, updated filters to handle sector and role name in various queries and contracts for more precise data retrieval. This improves handling of team and user data by enhancing search capabilities.
=> Enhance serialization and queries for better filtering

app/concepts/api/v1/questionnaires/serializers/show.rb, app/models/option.rb, app/models/question.rb, db/files/questions.rb, db/migrate/20240911153521_add_label_to_container_type.rb, db/migrate/20240912143748_add_aditional_info_to_question.rb, db/migrate/20240912143921_add_aditional_info_to_option.rb, db/migrate/20240913160329_add_group_to_options.rb, db/migrate/20240913161608_remove_text_area_and_add_type_option_to_option.rb, db/schema.rb, db/seeds.rb
Include migrations to add columns for container types, questions, and options. Also, update the seed tasks to ensure the necessary initial data is created or cleared before seeding new data.
=> Add database migrations and update questions data

db/files/questions.rb
This PR updates the first question from the questionnaire
=> fix: update seed

app/concepts/api/v1/questionnaires/operations/current.rb, app/models/elimination_method_type.rb, db/files/questions.rb, db/migrate/20240901233318_add_languagues_to_question.rb, db/migrate/20240901233500_add_languagues_to_option.rb, db/migrate/20240906151850_remove_in_use_to_inspections.rb, db/migrate/20240906152336_add_water_source_other_to_inspections.rb, db/migrate/20240906154413_remove_has_lid_to_inspections.rb, db/migrate/20240906154539_add_new_fields_by_lid_to_inspects.rb, db/migrate/20240918204605_add_languages_to_elimination_method_types.rb, db/schema.rb
Added language-specific columns (name_en, name_es, name_pt) to several tables to support multilingual entries. Updated seed files and models accordingly. Included other migrations to refine inspection attributes and ensure data consistency.
=> Add multilingual support to EliminationMethodTypes and Options

Gemfile.lock, app/concepts/api/v1/visits/operations/create.rb, app/concepts/api/v1/visits/serializers/show.rb, app/models/special_place.rb, config/initializers/constants/visit_params.rb, db/migrate/20240919130245_add_internationalization_to_special_places.rb, db/schema.rb, db/seeds.rb
Special Places with Data provided by Amy
=> Special Places with Data provided by Amy

Gemfile, Gemfile.lock, config/environment.rb, config/rollbar.rb
Configured Rollbar for asynchronous error logging in Rails. Integrated synchronous fallback in case of async failure.
=> Add Rollbar for error tracking

app/concepts/api/v1/wedges/queries/index.rb
Modified the query to include a join with the sector table for enhanced data retrieval. Fixed filtering logic for name and sector_id clauses to reference the correct column and handle nil values appropriately.
=> Update Wedge query to join with sector and correct filters.

app/concepts/api/v1/users/accounts/contracts/change_team.rb, app/concepts/api/v1/users/accounts/operations/change_team.rb
Added a `user_id` parameter to the contract and validation logic to check if the user exists. Updated the `update_user` method to retrieve and update the correct user profile based on the provided `user_id`, improving the flexibility of the team change operation.
=> Enhance team change operation by supporting user ID

app/concepts/api/v1/posts/contracts/index.rb, app/concepts/api/v1/users/accounts/serializers/user_profile.rb
Enhanced the user profile serializer to include sector and wedge details for the team. Removed redundant sector existence validation in the post contracts index.
=> Update user profile serializer and remove sector validation

db/files/questions.rb
This PR implements [265](https://denguechat.atlassian.net/browse/DNG-265)
=> fix: Show No permanentes containers types first

app/concepts/api/v1/posts/contracts/create.rb, app/concepts/api/v1/posts/operations/index.rb, app/concepts/api/v1/posts/operations/show.rb, app/concepts/api/v1/posts/queries/index.rb, app/concepts/api/v1/posts/queries/show.rb, app/concepts/api/v1/posts/serializers/index.rb, app/concepts/api/v1/posts/serializers/show.rb, app/models/inspection_type_content.rb, app/models/post.rb, db/migrate/20241004012438_add_visibility_to_post.rb, db/migrate/20241004015238_fill_visibility_for_existing_post.rb, db/schema.rb
I added the visibility feature to Post modules, I changed the create, index and show endpoint based to the new attribute.
=> Add Visibility to Posts

app/concepts/api/v1/users/accounts/operations/create.rb
Change business logic to create user and assign the brigadista rol by default
=> Change business logic to create user and assign the brigadista rol by default 

app/models/inspection.rb, db/files/questions.rb, db/migrate/20241004031609_add_other_elimination_method_to_inspection.rb, db/migrate/20241004032023_add_otro_option_in_questions.rb, db/schema.rb
Add new options in the question "¿Qué acción se realizó con el contenedor?"
Added other option as text area.
=> Add new options in the question "¿Qué acción se realizó con el contenedor?"  Added other option as text area.

app/concepts/api/v1/get_address/decorators/address_decorator.rb
I choose a short description of address without country and city
=> get address refactoring

app/concepts/api/v1/posts/operations/index.rb, app/concepts/api/v1/posts/queries/index.rb, app/concepts/api/v1/posts/serializers/show.rb
=> Fix posts paginate and filter

app/concepts/api/v1/get_address/decorators/address_decorator.rb, app/concepts/api/v1/posts/operations/index.rb, app/concepts/api/v1/posts/queries/index.rb, app/concepts/api/v1/posts/serializers/show.rb
Fix pagination on posts endpoint
=> Fix pagination on posts endpoint

app/concepts/api/v1/reports/contracts/house_status.rb, app/concepts/api/v1/reports/operations/house_status.rb, app/concepts/api/v1/reports/queries/house_status.rb, app/concepts/api/v1/reports/serializers/house_status.rb, app/controllers/api/v1/reports_controller.rb
add new fields for the team reports
=> add new fields for the team reports

app/concepts/api/v1/posts/contracts/create.rb, app/concepts/api/v1/posts/contracts/update.rb, app/concepts/api/v1/reports/queries/house_status.rb, db/files/questions.rb
fix typo errors, and validation errors on posts
=> fix typo errors, and validation errors on posts

app/concepts/api/v1/posts/contracts/create.rb, app/concepts/api/v1/posts/contracts/update.rb
change the content permited lenght in posts
=> change the content permited lenght in posts

app/concepts/api/v1/visits/contracts/inspection.rb, app/concepts/api/v1/visits/operations/create.rb
=> fix contracts to visits

app/concepts/api/v1/reports/queries/house_status.rb, app/concepts/api/v1/reports/serializers/house_status.rb, app/workers/reports/house_status.rb, db/migrate/20241010163228_fix_question_and_option_in_seed.rb
fix house reports with integers
=> fix house reports with integers

app/concepts/api/v1/posts/queries/index.rb
=> fix like_by_me

app/concepts/api/v1/posts/queries/index.rb, app/concepts/api/v1/questionnaires/serializers/show.rb, app/concepts/api/v1/visits/operations/create.rb, db/files/questions.rb, db/schema.rb
=> fix like by user

app/concepts/api/v1/reports/contracts/brigadist_performance.rb, app/concepts/api/v1/reports/operations/brigadist_performance.rb, app/concepts/api/v1/reports/queries/brigadist_performance.rb, app/concepts/api/v1/reports/queries/brigadist_performance_green_houses.rb, app/concepts/api/v1/reports/serializers/brigadist_performance.rb, app/controllers/api/v1/reports_controller.rb, config/initializers/constants/error_codes.rb, config/routes.rb, db/migrate/20241011163552_change_question_quantity_founded_option.rb, db/seeds.rb
report for user perfomance (visits & green houses)
=> report for user perfomance (visits & green houses)

db/files/questions.rb
This PR fixes two small bugs related to the questionnaire
=> fix: Fix values and references

app/concepts/api/v1/comments/operations/destroy.rb, app/concepts/api/v1/comments/operations/show.rb, app/concepts/api/v1/comments/operations/update.rb, app/concepts/api/v1/posts/operations/destroy.rb, app/concepts/api/v1/posts/operations/update.rb, app/concepts/api/v1/posts/queries/index.rb, app/concepts/api/v1/posts/queries/show.rb, app/concepts/api/v1/posts/serializers/show.rb
The teams leader's can edit/delete all the posts and comments like a moderator
=> add edit and delete a post by user, team_leader or admin

app/concepts/api/v1/questionnaires/serializers/show.rb, app/models/breeding_site_type.rb, app/models/breeding_site_type_aditional_information.rb, db/migrate/20241018183407_create_breeding_site_type_aditional_informations.rb, db/schema.rb
additional information feature
=> additional information feature

app/concepts/api/v1/comments/operations/destroy.rb, app/concepts/api/v1/comments/operations/show.rb, app/concepts/api/v1/comments/operations/update.rb, app/concepts/api/v1/posts/operations/destroy.rb, app/concepts/api/v1/posts/operations/update.rb, app/concepts/api/v1/posts/queries/index.rb, app/concepts/api/v1/posts/queries/show.rb, app/concepts/api/v1/posts/serializers/show.rb
Add position attr to options because we need to reorder some options of the questions from the backend.
=> Add position attr to options because we need to reorder some options of the questions from the backend.

app/concepts/api/v1/questionnaires/serializers/show.rb, app/models/question.rb, db/files/questions.rb, db/migrate/20241023133019_add_notes_to_question.rb, db/migrate/20241023133155_change_visit_workflow_by_content_in_containers.rb, db/schema.rb
Change the visist workflow if the brigadist found larvae, pupae, or eggs
=> Change the visist workflow if the brigadist found larvae, pupae, or eggs

db/migrate/20241031114743_enable_unnacent.rb, db/schema.rb
Fix users filters that use unnacent
=> Fix users filters that use unnacent

app/concepts/api/v1/users/accounts/operations/index.rb, app/concepts/api/v1/users/accounts/queries/index.rb, app/concepts/api/v1/visits/contracts/create.rb, app/concepts/api/v1/visits/operations/create.rb, app/models/user_account.rb
Changes to visits, (when inspections is null)
=> Changes to visits, (when inspections is null)

app/concepts/api/v1/visits/contracts/create.rb
fix comparation in visit contract string and integer
=> fix comparation in visit contract string and integer

app/concepts/api/v1/visits/operations/create.rb
change inspection[:quantity_founded] to integer because mobile send sometimes a string
=> change inspection[:quantity_founded] to integer because mobile send sometimes a string

app/concepts/api/v1/visits/operations/create.rb, app/models/inspection.rb, db/migrate/20241104204356_change_elimination_method_type_in_visits.rb, db/migrate/20241104210049_change_container_protection_in_visits.rb, db/schema.rb
Change to nullable container_protection to inspection
=> Change to nullable container_protection to inspection

app/concepts/api/v1/visits/operations/create.rb
fix visits create when a inspection hasn't water inside
=> fix visits create when a inspection hasn't water inside

app/concepts/api/v1/visits/operations/create.rb
fix visits create when a inspection hasn't water inside
=>  fix visits create when a inspection hasn't water inside 

app/concepts/api/v1/users/accounts/operations/destroy.rb
remove deleted users to teams or as leader in a team
=> remove deleted users to teams or as leader in a team

app/concepts/api/v1/teams/contracts/create.rb, app/concepts/api/v1/teams/contracts/update.rb
=> remove leader to teams

app/concepts/api/v1/visits/operations/create.rb, app/models/inspection.rb, app/models/visit.rb, db/migrate/20241115234651_add_resume_to_visits_and_inspections.rb, db/migrate/20241115235615_add_color_to_inspection.rb, db/schema.rb
=> improve reports

app/concepts/api/v1/visits/operations/create.rb
remove deleted users to teams or as leader in a team #274
=>  remove deleted users to teams or as leader in a team #274 

app/concepts/api/v1/visits/operations/create.rb
=> hot fix language create visit

app/concepts/api/v1/users/accounts/queries/index.rb
fix brigadist searcher when user put some spaces
=> fix brigadist searcher when user put some spaces

app/concepts/api/v1/visits/serializers/index.rb
Fix/525/incorrect site data display in reports and visit view
=> I use reference code instead id

config/application.rb
=> Change the zone time to Peru

app/concepts/api/v1/visits/operations/create.rb
=> fix color logic on inspection

app/concepts/api/v1/reports/operations/house_status.rb, app/concepts/api/v1/reports/queries/house_status_web.rb
=> fix house status for the web

app/controllers/web/change_images_controller.rb, app/views/change_images/options.html.erb, config/routes.rb
=> changes on images endpoint

app/concepts/api/v1/users/accounts/contracts/create.rb
=> Email is not required

app/concepts/api/v1/house_blocks/queries/index.rb, app/concepts/api/v1/users/accounts/operations/validate_code.rb
fix: Fix the house_blocks endpoint according to the ticket
=> fix: Fix the house_blocks endpoint according to the ticket

app/concepts/api/v1/house_blocks/queries/index.rb, app/concepts/api/v1/users/accounts/operations/validate_code.rb
Fix the facilitator info on team list
=> Fix the facilitator info on team list

app/concepts/api/v1/inspections/operations/update.rb, app/concepts/api/v1/reports/queries/brigadist_performance_green_houses.rb
fix: Fix query to get the green house by brigadists
=> fix: Fix query to get the green house by brigadists

app/concepts/api/v1/reports/contracts/tariki_house.rb, app/concepts/api/v1/reports/operations/tariki_house.rb, app/concepts/api/v1/reports/queries/tariki_house.rb, app/concepts/api/v1/reports/serializers/tariki_house.rb, app/controllers/api/v1/reports_controller.rb, app/models/house.rb, config/routes.rb, db/migrate/20241223143202_add_tariki_status_to_houses.rb, db/schema.rb
fix: Fix the tariki houses endpoint
=> fix: Fix the tariki houses endpoint

Gemfile, Gemfile.lock, app/concepts/api/v1/users/lib/create_tokens.rb, app/concepts/api/v1/users/sessions/operations/create.rb, app/controllers/api/v1/users/sessions_controller.rb, config/initializers/constants/user.rb
fix: I add new logic to login, this change it's about the token duration between mobile and web clients
=> fix: token persistence

app/concepts/api/v1/teams/queries/index.rb, app/concepts/api/v1/visits/queries/index.rb
fix: Fix sort columns in teams and visits index
=> fix: Fix sort columns in teams and visits index

app/concepts/api/v1/organizations/queries/index.rb, app/concepts/api/v1/special_places/queries/index.rb
fix: Fix sort columns in organizations and special places index
=> fix: Fix sort columns in organizations and special places index

app/concepts/api/v1/visits/queries/index.rb
fix: Fix sort columns in visits by wedge
=> fix: Fix sort columns in visits by wedge

app/concepts/api/v1/reports/queries/house_status_mobile.rb
=> fix: Fix filters on mobile

app/controllers/api/v1/visits_controller.rb, app/models/inspection.rb, app/models/visit.rb
I configure paper trail to save audit info about changes in inspection.rb and visit.rb
=> I configure paper trail to save audit info

app/concepts/api/v1/reports/queries/house_status_mobile.rb
=> fix the counters visits tabs

app/external_services/gis.rb
=> I create a connector to GIS

config/initializers/pagy.rb
=> Fix pagy page number.

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, config/application.rb, config/initializers/rack_attack.rb, config/routes.rb
=> Add and setup rack-attack

app/concepts/api/v1/house_blocks/contracts/create.rb, app/concepts/api/v1/house_blocks/contracts/update.rb, app/concepts/api/v1/house_blocks/operations/create.rb, app/concepts/api/v1/house_blocks/operations/update.rb, app/concepts/api/v1/house_blocks/serializers/show.rb, app/concepts/api/v1/houses/contracts/orphan_house.rb, app/concepts/api/v1/houses/operations/orphan_house.rb, app/concepts/api/v1/houses/queries/orphan_house.rb, app/concepts/api/v1/houses/serializers/index.rb, app/controllers/api/v1/house_blocks_controller.rb, app/controllers/api/v1/houses_controller.rb, app/models/house.rb, config/initializers/constants/error_codes.rb, config/initializers/constants/permission_codes.rb, config/routes.rb
Create endpoints to manage house_blocks and their houses
=> Create endpoints to manage house_blocks and their houses

app/concepts/api/v1/users/accounts/operations/index.rb, app/controllers/application_web_controller.rb, app/controllers/web/sync_logs_controller.rb, app/external_services/gis/house.rb, app/models/sync_log.rb, app/models/sync_log_error.rb, app/views/layouts/application_web.html.erb, app/views/web/sync_logs/index.html.erb, app/views/web/sync_logs/show.html.erb, config/initializers/constants/error_codes.rb, config/routes.rb, db/migrate/20250123031612_create_sync_log.rb, db/migrate/20250123031846_create_sync_log_error.rb, db/schema.rb
Little place to control houses sync
=> Little place to control houses sync

app/concepts/api/v1/wedges/contracts/index.rb, app/concepts/api/v1/wedges/queries/index.rb
feature: create endpoint wedges
=> feature: create endpoint wedges

app/concepts/api/v1/inspections/contracts/update.rb, app/concepts/api/v1/inspections/operations/update.rb, app/concepts/api/v1/inspections/queries/index.rb, app/concepts/api/v1/inspections/queries/show.rb, app/concepts/api/v1/inspections/serializers/index.rb, app/concepts/api/v1/inspections/serializers/show.rb, app/concepts/api/v1/inspections/serializers/show_without_questionnaire.rb, app/concepts/api/v1/visits/contracts/create.rb, app/concepts/api/v1/visits/operations/create.rb, app/concepts/api/v1/visits/serializers/show.rb, app/models/container_protection.rb, app/models/inspection.rb, app/models/inspection_container_protection.rb, db/migrate/20250211141712_change_container_protection_relation_to_inspections.rb, db/migrate/20250211154644_add_many_container_protections_to_inspections.rb, db/schema.rb
I changed the relation between inspection and container protection, and then I migrated the old data to the new table.
=> fix: Container protection as array 

app/concepts/api/v1/visits/operations/create.rb, db/migrate/20250530044216_remove_question_about_water_to_questionnaire.rb, db/schema.rb
All newly registered containers store has_water = true automatically
No question for water presence remains in the questionnaire flow
Endpoint change tested with mobile client
=>     Migration executed and verified in staging

db/migrate/20250606110027_change_position_and_text_to_container_protection_options.rb, db/schema.rb
In the visit flow, when a user lays on the El envase esta protegido?view, please make 2 changes
Put the option “Otro tipo de proteccion“ as last option, and
Change to lower case the word “Diario“
=> Change position and text to Protection Options

db/migrate/20250606113309_change_type_field_in_question.rb, db/migrate/20250606115001_change_text_on_question_about_water.rb, db/schema.rb
Update the questionnaire to add a new option under the question "En este recipiente hay":
"No pude revisar el envase." (to appear below the "Nada" option)
=> Update "en este recipiente hay"

app/concepts/api/v1/teams/serializers/show.rb, app/concepts/api/v1/visits/operations/create.rb, app/models/team.rb, db/seeds.rb
[DNG-947](https://denguechat.atlassian.net/browse/DNG-947?atlOrigin=eyJpIjoiYTUxODlmMGZlMzgyNGNmZGJlMjlmOTlkOTc5N2FjZTciLCJwIjoiaiJ9)
=> Allow changing the owner of a visit

lib/tasks/data_migration.rake
[DNG-935](https://denguechat.atlassian.net/browse/DNG-935)
=> Add new options to the "¿Qué información compartiste?" question
