Gemfile, app/models/user_account.rb, app/models/user_profiles_role.rb, db/migrate/20240624144825_create_versions.rb, db/migrate/20240624144826_add_object_changes_to_versions.rb, db/schema.rb
A new table called 'versions' has been created for audit logs. This table is going to store history of record changes in the system. Additionally, the schema has been updated and 'paper_trail' gem has been added to the Gemfile for version management. Also, minor modifications have been done in 'user_profiles_role' and 'user_account's' models.
=> Add 'versions' table and update schema

app/concepts/api/v1/lib/paginates/paginate.rb, app/concepts/api/v1/lib/queries/query_helper.rb, app/concepts/api/v1/lib/services/pagy.rb, app/concepts/api/v1/organizations/contracts/index.rb, app/concepts/api/v1/organizations/operations/index.rb, app/concepts/api/v1/organizations/operations/show.rb, app/concepts/api/v1/organizations/queries/index.rb, app/concepts/api/v1/organizations/serializers/index.rb, app/controllers/api/v1/organizations_controller.rb, app/decorators/organization_decorator.rb, app/models/organization.rb, config/routes.rb, db/migrate/20240626071306_create_organizations.rb, db/schema.rb
This commit introduces the organizations endpoint to the API with added features for pagination and sorting. It includes the implementation of new classes and modules for managing pagination, handling queries and various test cases. It also ensures compliance with the Organization's model, serializers and decorators. Additionally, it includes the creation of the organizations table in the database.
=> Add organizations endpoint with pagination and sorting

app/concepts/api/v1/lib/serializers/naming_convention.rb, app/concepts/api/v1/users/sessions/operations/create.rb
A new NamingConvention class has been introduced in the API v1 library serializers. This class helps in converting the key/value pairs of given parameters to snake case or camel case. Additionally, NamingConvention serializer usage has been added in the create session operation to format the JWT token.
=> Add NamingConvention serializer in API v1 lib

app/lib/services/compose_render_hash.rb
A new parameter 'meta' has been added to the compose_render_hash method to expand its functionalities. This update ensures that the method can accommodate more diverse data requirements, managing them efficiently within different environments.
=> Add meta parameter to compose_render_hash

app/concepts/api/v1/locations/contracts/index.rb
The location contract's parameters have been restructured for better clarity. The 'country_id' parameter no longer stands alone and is instead nested under the 'filter' parameter, which is now required. The 'country_id' inside 'filter' is also now required and must be a string.
=> Refactor location contract parameters

db/seeds.rb
The changes made ensure that both city and neighborhood objects are properly persisted when running the database seeding script. Previously, cities were being created correctly, but neighborhoods were simply being instantiated without being saved in the database. This fix ensures all data is correctly saved.
=> Fix object persistence in seeding script

app/concepts/api/v1/users/accounts/operations/create.rb
A new operation 'to_snake_case' has been added to the user account creation process. This operation converts incoming parameters to snake_case using the 'NamingConvention' serializer, ensuring the parameters adhere to the general naming convention standards across the application.
=> Add snake_case conversion to user account creation

config/database.yml
The database name for the test environment has been updated from 'denguechat_plus_test' to 'denguechat_plus_test2'. Additionally, the username for the production database is now fetched from the environment variable 'DENGUECHAT_PLUS_DATABASE_USER' instead of being hardcoded as 'denguechat_plus'.
=> Update database configuration for test and production

app/concepts/api/v1/organizations/queries/update.rb
The class name in api/v1/organizations/queries/update.rb file was mistakenly named Index instead of Update. This commit corrects the class name, aligning it with the file's purpose.
=> Rename class in update.rb from Index to Update

app/concepts/api/v1/teams/queries/update.rb
The commit changes the name of the class from Index to Update in Teams Queries module. This is done to correctly represent the functionality of the class, which involves updates not indexing.
=> Rename class Index to Update in Teams Queries

app/controllers/concerns/http_auth_concern.rb
The http_authenticate method was previously called before each action in the HTTP authentication controller. This updates the code to comment out this line, effectively deactivating the before action call to the http_authenticate method.
=> Deactivate http_authenticate before_action

app/concepts/api/v1/organizations/operations/update.rb, app/concepts/api/v1/teams/contracts/create.rb, app/concepts/api/v1/teams/contracts/destroy.rb, app/concepts/api/v1/teams/contracts/update.rb, app/concepts/api/v1/teams/operations/create.rb, app/concepts/api/v1/teams/operations/update.rb, app/concepts/api/v1/teams/queries/update.rb, app/concepts/api/v1/teams/serializers/index.rb, app/concepts/api/v1/teams/serializers/member.rb, app/concepts/api/v1/teams/serializers/show.rb, app/models/team.rb, config/routes.rb
The code changes primarily involve refactoring of team-related operations - create, update and destroy. Creation and updating of team members have been enhanced with checks for existing team members and user accounts. A functionality to destroy team members has also been added. Additionally, serializer changes allow team operations to include 'organization'. The handling of update operations has been improved within a transaction block. This also involves necessary changes in routes and model settings to support these operations.
=> Refactor team-related modules and routes

app/concepts/api/v1/countries/serializers/index.rb, app/concepts/api/v1/states/serializers/index.rb, app/concepts/api/v1/users/accounts/contracts/create.rb, app/concepts/api/v1/users/sessions/contracts/create.rb
Refactoring was performed on the user account validation logic to handle optional gender and to add entity existence checks for neighborhood and city references. The serializer in country and state modules incorrectly referenced kept neighborhoods. This has been corrected to reference kept states and cities respectively.
=> Refactor user validation and correct serializers

app/concepts/api/v1/users/sessions/contracts/create.rb
In the file 'create.rb' under 'app/concepts/api/v1/users/sessions/contracts', the module name has been changed from Accounts to Sessions. This refactoring improves the context of the module, making its purpose and content clearer.
=> Refactor module name from Accounts to Sessions

app/concepts/api/v1/users/sessions/operations/create.rb
This commit updates the failure types and error messages for user authentication. It provides more detailed responses when authentication fails, making use of differing error types and messages depending on whether the failure is due to wrong credentials or a user account without confirmation.
=> Update authentication failure types and messages

app/concepts/api/v1/roles/contracts/index.rb, app/concepts/api/v1/roles/operations/index.rb, app/concepts/api/v1/roles/queries/index.rb, app/concepts/api/v1/roles/serializers/index.rb, app/concepts/api/v1/roles/serializers/permission.rb, app/controllers/api/v1/roles_controller.rb, config/routes.rb
A new API endpoint has been set up to retrieve roles, including the necessary operations, queries, and serializers. This includes the addition of a new route and its associated controller method. Additionally, a contract for validating query parameters and a serializer for permissions related to these roles have been introduced.
=> Add API endpoint for role retrieval

Gemfile
In the Gemfile, the 'sidekiq', 'sidekiq-limit_fetch', and 'sidekiq-scheduler' gems have been updated to use specific versions. This ensures more predictable builds and potentially reduces issues related to gem versions.
=> Update Sidekiq gems to specific versions

config/initializers/constants/user.rb
Update FILTERS constant in user initializer 
Filter options have been updated to include 'username' and 'phone' in the list of filterable fields for user accounts. This will give more flexibility when filtering user data.
=> Update FILTERS constant in user initializer

app/concepts/api/v1/users/accounts/serializers/show_current_user.rb, app/concepts/api/v1/users/sessions/serializers/create.rb
The previous code used to present the roles and permissions of a user in a joined string format. This commit adjusts the code to return them as arrays instead, which are more manageable and easier to work with. The changes apply to both the 'show_current_user' and 'create' serializers.
=> Modify role and permission serialization

app/controllers/api/v1/organizations_controller.rb
The current_user option was removed from the Organizations controller. It was not being used in the Index and Show actions for rendering. Since it was not providing any value, it's better to remove the unused code to make the codebase cleaner and easier to understand.
=> Remove unused current_user option in API

app/concepts/api/v1/users/accounts/operations/show.rb, app/concepts/api/v1/users/accounts/serializers/show.rb, app/controllers/api/v1/users_controller.rb, app/models/user_profile.rb, config/routes.rb
Added a new 'show' endpoint to the users API for displaying individual user profiles. This involved creating and integrating the corresponding operation, serializer, and route. Roles have also been delegated to the user account in the UserProfile model.
=> Add show user endpoint

app/concepts/api/v1/users/accounts/contracts/update.rb, app/concepts/api/v1/users/accounts/operations/update.rb
The password parameter has been added to the API v1 update user account contract and operation. This change includes validating the password's minimum length and processing the password update within the attributes passed to the model's update function.
=> Add password parameter to user account update

app/concepts/api/v1/get_last_params/contracts/index.rb, app/concepts/api/v1/get_last_params/operations/index.rb, app/concepts/api/v1/get_last_params/queries/index.rb, app/concepts/api/v1/get_last_params/serializers/index.rb, app/controllers/api/v1/get_last_params_controller.rb, app/models/place.rb, app/models/visit_param_version.rb, app/models/water_source_type.rb, config/initializers/constants/visit_params.rb, config/routes.rb, db/migrate/20240725061011_create_visit_param_versions.rb, db/migrate/20240725080730_remove_category_from_places.rb, db/schema.rb, db/seeds.rb
Add GetLastParams endpoint with index operations
Implemented the GetLastParams endpoint in the API, including creation of Contracts, Operations, Queries, and Serializers for handling visit parameter versions. Added related database migrations, including the creation of the visit_param_versions table and removal of the category column from the places table.
=> Add GetLastParams endpoint with index operations

app/concepts/api/v1/users/accounts/contracts/update.rb, app/concepts/api/v1/users/accounts/serializers/show_current_user.rb, config/initializers/constants/error_codes.rb, config/initializers/dry_validation.rb
Enhanced email, neighborhood, city, organization, and team validations to check existence more robustly. Updated phone and username validation logic to ensure uniqueness excluding the current user. Added `transform_params` method to `Dry::Validation::Contract` to handle parameter transformation for the update action and included `phone` attribute in the current user serializer output.
=> Update validation logic and add phone to user serializer

app/concepts/api/v1/users/accounts/serializers/show_current_user.rb, app/concepts/api/v1/users/accounts/serializers/user_profile.rb, app/concepts/api/v1/users/sessions/serializers/create.rb, db/seeds.rb
Removed 'new' action from seed permissions; added 'confirm_account' permission for admin role. Enhanced serializers to check for blank fields before accessing attributes and updated permission formatting to use hyphens.
=> Update seeds and serializers for permissions and blank checks

app/concepts/api/v1/users/accounts/serializers/index.rb
This change introduces a new attribute, `roles`, to the user account serializer. The `roles` attribute includes the ID and name of each role associated with a user, enhancing the API response with more detailed user information.
=> Add roles attribute to user account serializer

app/concepts/api/v1/cities/contracts/create.rb, app/concepts/api/v1/cities/operations/create.rb
Improve error handling by formatting detailed error messages when city creation fails. Also, add a validation rule to ensure the provided state ID exists within the database.
=> Fix city creation error handling and add state ID validation

app/concepts/api/v1/special_places/operations/index.rb
Corrected the key from 'special_place.name' to 'special_places.name' in the default sorting logic. This ensures consistency with the expected parameter naming convention.
=> FIX error typo

app/concepts/api/v1/users/sessions/serializers/create.rb
This commit adds a new `country` attribute to the user session serializer to include country details based on the user's city information. The country attribute will contain the country’s ID and name, assuming city data is present and valid. This enhancement aids
=> Add country attribute to user session serializer

app/models/house.rb, app/models/house_block.rb, db/migrate/20240807071033_create_house_blocks.rb, db/migrate/20240807181557_create_houses.rb, db/schema.rb
Introduced new models, House and HouseBlock, alongside their respective database migrations. The House model includes multiple references to other entities, while HouseBlock has associations with houses, teams, and user profiles. This update also includes schema changes to integrate these models and their relationships into the database.
=> Add House and HouseBlock models with migrations

app/concepts/api/v1/teams/contracts/create.rb, app/concepts/api/v1/teams/contracts/update.rb, app/concepts/api/v1/teams/serializers/index.rb, config/initializers/constants/permission_codes.rb
Updated variable names and attributes to use "member" instead of "user_profile" for consistency across serializers and contracts. Additionally, added a new permission code for changing user status.
=> Refactor team member terminology

app/concepts/api/v1/teams/contracts/update.rb
Eliminated unnecessary validation checks ensuring user profiles were not assigned to a brigade. This streamlines the validation process while maintaining the integrity of member ID assignments.
=> Remove redundant user profile validation

app/concepts/api/v1/teams/contracts/update.rb
Previously, the validation only checked if the name existed in the database, which caused issues during updates. Now, it excludes the current team's ID from the check, allowing teams to update without unnecessary uniqueness conflicts.
=> Update team name uniqueness validation logic

app/concepts/api/v1/questionnaires/serializers/show.rb, db/seeds.rb
Corrected the assignment of permissions in the seed file to use the shovel operator for array accumulation. Also modified the JSON serializer to properly camelCase keys and added the 'next' field to the options.
=> Fix seed permissions assignment and update JSON keys

app/concepts/api/v1/houses/contracts/index.rb, app/concepts/api/v1/houses/contracts/list_to_visit.rb, app/concepts/api/v1/houses/operations/list_to_visit.rb, app/concepts/api/v1/houses/queries/list_to_visit.rb
Introduced a filter parameter to the ListToVisit query for houses, allowing searches using a reference code. Updated relevant contracts and operations to support the new filtering capability.
=> Add filtering by reference code to house queries

app/concepts/api/v1/questionnaires/serializers/show.rb, app/concepts/api/v1/visits/contracts/create.rb, db/files/questions.rb
Removed unnecessary team_id existence validation rule from the visits create contract. Improved descriptions for certain questions in the db/files/questions.rb file to provide clearer guidance. Additionally, the questionnaires serializer now includes question descriptions.
=> Remove team_id validation and update question descriptions

app/concepts/api/v1/house_blocks/serializers/index.rb, app/concepts/api/v1/houses/serializers/list_to_visit.rb, app/concepts/api/v1/users/accounts/contracts/change_team.rb, app/concepts/api/v1/users/accounts/operations/change_team.rb, app/concepts/api/v1/users/accounts/serializers/show.rb, app/concepts/api/v1/users/accounts/serializers/user_profile.rb, app/concepts/api/v1/visits/operations/create.rb, app/controllers/api/v1/users_controller.rb, app/models/house_block.rb, config/initializers/constants/permission_codes.rb, config/routes.rb, db/migrate/20240830070903_change_user_profile_and_team_in_house_blocks.rb, db/schema.rb, db/seeds.rb
Implemented a new `change_team` operation, including validation contracts and necessary migrations. Updated serializers and seeds to account for team changes. Adjusted house block model and related schemas to support optional team and user profile relationships.
=> Add change team functionality for user accounts

app/concepts/api/v1/teams/contracts/index.rb, app/concepts/api/v1/teams/queries/index.rb
Introduce 'wedge_id' and 'wedge' parameters to the team queries and contract filters. This allows filtering teams based on wedge data, enhancing query specificity and flexibility.
=> Add wedge filters to team queries

app/concepts/api/v1/teams/serializers/show.rb
This commit introduces two new attributes to the team serializer: `visits`, which counts the number of visits associated with a team, and `sites_statuses`, which groups and counts houses by their status for a team. These additions enhance
=> Add team visits and site statuses to team serializer

app/concepts/api/v1/visits/contracts/inspection.rb, app/models/inspection.rb, db/migrate/20240906151850_remove_in_use_to_inspections.rb, db/schema.rb
This migration removes the `in_use` boolean column from the inspections table. The related validator and model annotations are also updated to reflect this change. This cleanup is part of ongoing database and model optimizations.
=> Remove `in_use` column from inspections

app/concepts/api/v1/visits/contracts/inspection.rb, app/models/inspection.rb, db/migrate/20240906152336_add_water_source_other_to_inspections.rb, db/schema.rb, db/seeds.rb
This commit introduces a new column `water_source_other` to the inspections table to allow for additional water source types. It also updates the corresponding seed data and validations to accommodate the new field.
=> Add water_source_other to inspections

app/concepts/api/v1/visits/contracts/inspection.rb, app/models/inspection.rb, db/migrate/20240906154413_remove_has_lid_to_inspections.rb, db/migrate/20240906154539_add_new_fields_by_lid_to_inspects.rb, db/schema.rb
Removed the `has_lid` column from inspections table and replaced it with `lid_type` and `lid_type_other` fields. Updated schema and related files to reflect these changes.
=> Remove has_lid column and add lid_type fields

app/models/container_protection.rb, app/models/inspection.rb, app/models/inspection_type_content.rb, app/models/type_content.rb, db/migrate/20240911130841_create_container_protections.rb, db/migrate/20240911132601_create_type_content.rb, db/schema.rb, db/seeds.rb
This commit introduces two new models: ContainerProtection and TypeContent along with their respective migrations. Enhancements include associations between Inspections and these new models, and relevant seed data is also added to the seeds.rb file for initial setup.
=> Add models and migrations for container protections and type contents

app/models/container_type.rb, db/schema.rb, db/seeds.rb
Introduced a new 'container_type' field in the ContainerType model to differentiate between 'permanent' and 'non-permanent' types. Updated seed data script to populate this new field and adjusted the task name to avoid conflicts.
=> Add container_type to ContainerType model and seed data

app/concepts/api/v1/users/accounts/contracts/index.rb, app/concepts/api/v1/users/accounts/queries/index.rb
This commit enhances the user accounts query by introducing a new filter parameter `full_name`. The associated contract has been updated to include an optional `full_name` string which allows searching by either first or last name using a case-insensitive match.
=> Add full name filter to user accounts query

app/models/special_place.rb, config/initializers/constants/visit_params.rb, db/migrate/20240919130245_add_internationalization_to_special_places.rb, db/schema.rb, db/seeds.rb
Added 'name_es', 'name_en', and 'name_pt' columns to support internationalization while removing the old 'name' column. Updated seed data to reflect new structure and ensured seed tasks check for new conditions. Modified constant 'RESOURCES' to include 'special_places' for visit parameters.
=> Add internationalization to SpecialPlace model

app/concepts/api/v1/users/accounts/operations/update.rb
The update_user method now checks if user_profile_attributes exist before trying to access it. This prevents potential errors when user_profile_attributes is nil, ensuring the code runs smoothly even in edge cases.
=> Fix update_user method to handle missing user_profile_attributes

app/concepts/api/v1/cities/operations/index.rb, app/concepts/api/v1/cities/queries/index.rb, app/concepts/api/v1/houses/serializers/index.rb, app/concepts/api/v1/houses/serializers/list_to_visit.rb, app/concepts/api/v1/special_places/contracts/create.rb, app/concepts/api/v1/special_places/contracts/index.rb, app/concepts/api/v1/special_places/contracts/update.rb, app/concepts/api/v1/special_places/operations/index.rb, app/concepts/api/v1/special_places/queries/index.rb, app/concepts/api/v1/special_places/serializers/index.rb, app/concepts/api/v1/special_places/serializers/show.rb, app/concepts/api/v1/teams/queries/index.rb, app/models/special_place.rb, config/initializers/constants/permission_codes.rb, config/routes.rb
Updated multiple serializers and queries to support multilingual names (English, Spanish, Portuguese) for SpecialPlaces. Adjusted sorting logic to prioritize more relevant fields and enhanced routing and permission codes to better handle special places and other entities.
=> Add multilingual support for SpecialPlaces and enhance sort

app/concepts/api/v1/questionnaires/serializers/show.rb
This change updates the serializer to include the statusColor attribute for options in the questionnaire. This allows the front-end to properly display the color status of each option as intended.
=> Add statusColor to questionnaire serializer

app/concepts/api/v1/comments/contracts/destroy.rb, app/concepts/api/v1/comments/operations/destroy.rb, app/concepts/api/v1/posts/serializers/index.rb, app/controllers/api/v1/comments_controller.rb, app/models/comment.rb, app/models/post.rb, config/initializers/constants/error_codes.rb, config/routes.rb, db/migrate/20240920183327_change_deleted_at_to_discarded_at_to_comment.rb, db/schema.rb
Introduced soft delete functionality by replacing `deleted_at` with `discarded_at` for comments and posts. Added destroy operation and validation for comments, allowing only the comment owner or an admin to perform deletion. Also updated routes, controllers, and serializers accordingly.
=> Add soft delete for comments and implement comment deletion

app/concepts/api/v1/posts/contracts/destroy.rb, app/concepts/api/v1/posts/operations/destroy.rb, app/controllers/api/v1/posts_controller.rb, config/routes.rb
This commit introduces the ability to delete posts via the API. It includes a destroy contract for validation, an operation to handle the deletion logic, and updates to the routes and controller to support this new feature.
=> Add post deletion functionality

app/concepts/api/v1/wedges/contracts/index.rb, app/concepts/api/v1/wedges/queries/index.rb, app/concepts/api/v1/wedges/serializers/index.rb, config/routes.rb
Extended serializers to include sector attributes for wedges and modified queries to filter by sector_id. Also updated routes to include wedges resources and contracts to support sector_id filtering.
=> Add sector support for Wedges in serializers and queries

app/concepts/api/v1/teams/serializers/show.rb, config/initializers/constants/error_codes.rb, config/initializers/constants/permission_codes.rb, db/seeds.rb
Introduced a new permission 'change_team' for team leaders and updated seed data to reflect this. Added 'users_change_team' error and permission codes. Enhanced the team serializer to include the user's role.
=> Add permissions for changing team and update team serializer

db/seeds.rb
This commit adds a new seed task to assign the 'index' permission for the 'wedges' resource to 'team_leader' and 'admin' roles. It ensures the permission is created if it doesn't exist and only assigns it if not already present.
=> Add permissions for listing wedges

app/concepts/api/v1/wedges/queries/index.rb
Unescaped the name filter parameter before using it in the search query to ensure user-provided strings are correctly interpreted. This adjustment ensures that names containing special characters are properly handled in the search functionality.
=> Fix name search query in index action

app/concepts/api/v1/house_blocks/contracts/index.rb
This commit introduces an optional 'name' filter to the parameters in house blocks contracts. This enhancement allows filtering by name in addition to existing parameters. It improves the flexibility and granularity of the API filters.
=> Add optional 'name' filter to house blocks contracts

app/concepts/api/v1/comments/contracts/update.rb, app/concepts/api/v1/comments/operations/update.rb, app/concepts/api/v1/comments/serializers/show.rb, app/concepts/api/v1/posts/contracts/update.rb, app/concepts/api/v1/posts/operations/update.rb, app/concepts/api/v1/posts/serializers/show.rb, app/controllers/api/v1/comments_controller.rb, app/controllers/api/v1/posts_controller.rb, config/routes.rb
Implemented update contracts and operations for both posts and comments, enabling users to update their posts and comments. Adjusted the serializers to correctly handle photo attachments and modified routes to allow update actions.
=> Add update operations for posts and comments

app/concepts/api/v1/questionnaires/serializers/show.rb, app/models/option.rb, app/models/questionnaire.rb, db/files/questions.rb, db/migrate/20240923175211_add_value_and_disable_other_options_to_option.rb, db/schema.rb, db/seeds.rb
This migration adds two new columns, `value` and `disable_other_options`, to the `options` table. Updated associated files and serializers to support these new attributes and reflect them in the schema. Also updated seed tasks and relevant models accordingly.
=> Add `value` and `disable_other_options` to `Option` model

app/concepts/api/v1/comments/serializers/show.rb, app/concepts/api/v1/posts/serializers/index.rb, app/concepts/api/v1/posts/serializers/show.rb, db/files/questions.rb
This update adds a created_by attribute to the comment and post serializers, which includes user account details such as account ID, first name, and last name. This enhancement aims to provide more detailed user information within the serialized objects for comments and posts.
=> Add created_by attribute to serializers

app/concepts/api/v1/visits/contracts/house.rb, app/concepts/api/v1/visits/operations/create.rb, app/concepts/api/v1/visits/services/house_finder_by_coords_service.rb, app/models/house.rb, db/migrate/20241004021912_add_house_location_status_to_house.rb, db/schema.rb
Added the ability to save a house with a default coordinate and added a new attribute to house, the new attribute is for recognize the houses without coordinates.
=> Set default Latitude and Longitude for new houses without location information

config/initializers/sidekiq.rb, config/sidekiq.yml
re-active the crontab for sync databases between denguechatplus and GIS(berkeley)
=> Crontab for sync databases between denguechatplus and GIS

config/sidekiq.yml
re-active the crontab for sync databases between denguechatplus and GIS(berkeley)
=> re-active the crontab for sync databases

config/initializers/sidekiq.rb, config/initializers/sidekiq.yml, config/sidekiq.yml
re-active the crontab for sync databases between denguechatplus and GIS(berkeley)
=> re-active the crontab for sync database

app/concepts/api/v1/inspections/operations/update.rb, app/concepts/api/v1/points/services/transactions.rb, app/concepts/api/v1/visits/operations/create.rb, app/concepts/api/v1/visits/operations/update.rb, app/models/house.rb, db/migrate/20250416170101_create_param_for_tariki_point.rb, db/schema.rb
If tariki_point_same_date = true, all visits on the same day will be counted toward the total required to mark a house as tariki.
If tariki_point_same_date = false, visits occurring on the same day will not be counted multiple times toward the tariki threshold.
=> Update the business logic to include a new boolean parameter called tariki_point_same_date

db/migrate/20250530034811_modify_option_text_from_options.rb, db/schema.rb
Spanish: "Del grifo o de otro recipiente"
English: "From the faucet or from another container"
=> The first option of the water source question is updated to:

db/migrate/20250606111329_add_new_option_to_question_cointainer_content.rb, db/schema.rb
Update the questionnaire to add a new option under the question "En este recipiente hay":
"No pude revisar el envase." (to appear below the "Nada" option)
=> New ProtectionType
